sonar.projectKey=telemt_tdlib-obf
sonar.organization=telemt

sonar.sources=.

# исключения
sonar.exclusions=\
docs/**,\
sqlite/**,\
test/**,\
tools/**,\
build.html,\
**/*.java

sonar.coverage.exclusions=\
td/telegram/MessagesManagerLifecycle.cpp,\
td/telegram/StoryManagerLifecycle.cpp,\
tdutils/td/utils/tl_storers.h
